//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bremsstrahlung.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class RegistrationEfficiency : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegistrationEfficiency defaultInstance = ((RegistrationEfficiency)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegistrationEfficiency())));
        
        public static RegistrationEfficiency Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>RegistrationEfficiency/V05_Efficiency.txt</string>
  <string>RegistrationEfficiency/V01_Efficiency.txt</string>
  <string>RegistrationEfficiency/P_Efficiency.txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Geometries {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Geometries"]));
            }
            set {
                this["Geometries"] = value;
            }
        }
    }
}
